from __future__ import annotations

import csv
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .config import ToolConfig
from .models import LiquidProperties
from .units import k_to_c

STARCCM_RUN_TIMEOUT_SECONDS = 5 * 60
DEFAULT_REFRIGERANT_POLYNOMIAL_DEGREE = 4
REFRIGERANT_PROPERTY_WRITE_MODES = {"table", "polynomial"}
PROPERTY_CSV_COLUMNS = {
    "temperature": "Temperature (C)",
    "density": "Density (kg/m^3)",
    "specific_heat": "Equivalent Specific Heat (J/kg-K)",
    "thermal_conductivity": "Equivalent Thermal Conductivity (W/m-K)",
    "dynamic_viscosity": "Equivalent Dynamic Viscosity (Pa-s)",
    "enthalpy": "Enthalpy (J/kg)",
}


@dataclass(frozen=True)
class PropertyPolynomials:
    temperature_min_c: float
    temperature_max_c: float
    density: tuple[float, ...]
    specific_heat: tuple[float, ...]
    thermal_conductivity: tuple[float, ...]
    dynamic_viscosity: tuple[float, ...]
    enthalpy: tuple[float, ...]


def render_macro(
    config: ToolConfig,
    liquid: LiquidProperties,
    liquid_csv: Path | None,
    vapor_csv: Path,
    output_sim: Path,
) -> str:
    liquid_table_path = str(liquid_csv) if liquid_csv is not None else ""
    saturation_temperature_c = k_to_c(liquid.saturation_temperature_k)
    standard_state_temperature_c = k_to_c(liquid.standard_state_temperature_k)
    property_write_mode = config.refrigerant_property_write_mode.strip().lower()
    if property_write_mode not in REFRIGERANT_PROPERTY_WRITE_MODES:
        raise ValueError("refrigerant_property_write_mode must be table or polynomial.")
    polynomial_degree = max(0, int(config.refrigerant_polynomial_degree))
    vapor_polynomials = None
    liquid_polynomials = None
    if property_write_mode == "polynomial":
        vapor_polynomials = _fit_property_polynomials(vapor_csv, polynomial_degree)
        if config.liquid_property_mode == "table":
            if liquid_csv is None:
                raise ValueError("liquid_properties.csv is required for liquid polynomial material writes.")
            liquid_polynomials = _fit_property_polynomials(liquid_csv, polynomial_degree)
    vapor_entropy_assignment = ""
    vapor_entropy_log = '    sim.println("  Vapor Standard State Entropy J/kg-K = not available in source JSON");'
    if liquid.vapor_standard_state_entropy_j_per_kg_k is not None:
        vapor_entropy_assignment = (
            '    setConstantWithUnitsOrDefault(material, "star.energy.StandardStateEntropyProperty", '
            f'{liquid.vapor_standard_state_entropy_j_per_kg_k:.12g}, "J/kg-K", '
            f'{liquid.vapor_standard_state_entropy_j_per_kg_k:.12g}, "Vapor Standard State Entropy");\n'
        )
        vapor_entropy_log = (
            '    sim.println("  Vapor Standard State Entropy J/kg-K = '
            f'{liquid.vapor_standard_state_entropy_j_per_kg_k:.12g}");'
        )
    vapor_temperature_assignment = (
        "    setVaporTemperaturePolynomials(material);"
        if property_write_mode == "polynomial"
        else "    setVaporTemperatureTables(material, table);"
    )
    liquid_temperature_assignment = (
        "      setLiquidTemperaturePolynomials(material);"
        if property_write_mode == "polynomial"
        else "      setLiquidTemperatureTables(material, table);"
    )
    vapor_polynomial_constants = _java_polynomial_constants("VAPOR", vapor_polynomials)
    liquid_polynomial_constants = _java_polynomial_constants("LIQUID", liquid_polynomials)
    return f"""// Auto-generated by refprop-to-ccm. Edit the property mapping section if STAR-CCM+ reports missing paths.
package macro;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import star.common.*;
import star.base.neo.*;
import star.material.*;

public class apply_refprop_to_star extends StarMacro {{
  private Simulation sim;
  private final List<String> successfulWrites = new ArrayList<String>();
  private final List<String> failedWrites = new ArrayList<String>();
  private final List<String> skippedWrites = new ArrayList<String>();

  private static final String CONTINUUM_NAME = "{_java(config.continuum_name)}";
  private static final String LIQUID_PHASE_NAME = "{_java(config.liquid_phase_name)}";
  private static final String VAPOR_PHASE_NAME = "{_java(config.vapor_phase_name)}";
  private static final String VAPOR_SPECIFIC_HEAT_SOURCE = "{_java(config.vapor_specific_heat_source)}";
  private static final String LIQUID_PROPERTY_MODE = "{_java(config.liquid_property_mode)}";
  private static final String REFRIGERANT_PROPERTY_WRITE_MODE = "{_java(property_write_mode)}";
  private static final int REFRIGERANT_POLYNOMIAL_DEGREE = {polynomial_degree};
  private static final String LIQUID_TABLE = "{_java(liquid_table_path)}";
  private static final String VAPOR_TABLE = "{_java(str(vapor_csv))}";
  private static final String OUTPUT_SIM = "{_java(str(output_sim))}";
{vapor_polynomial_constants}
{liquid_polynomial_constants}

  public void execute() {{
    sim = getActiveSimulation();
    sim.println("[refprop-to-ccm] Using existing continuum: " + CONTINUUM_NAME);
    PhysicsContinuum continuum = getExistingContinuum();

    Material liquidMaterial = null;
    Material vaporMaterial = null;
    try {{
      Material[] materials = getExistingPhaseMaterials(continuum);
      liquidMaterial = materials[0];
      vaporMaterial = materials[1];
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Existing phase/material lookup failed: " + ex.getMessage());
      throw new RuntimeException("[refprop-to-ccm] Stop saving because target continuum/phase/material lookup failed.", ex);
    }}
    Table liquidTable = importLiquidTableBestEffort();
    Table vaporTable = importVaporTableBestEffort();
    if ("table".equals(LIQUID_PROPERTY_MODE) && "table".equals(REFRIGERANT_PROPERTY_WRITE_MODE) && liquidTable == null) {{
      throw new RuntimeException("[refprop-to-ccm] Stop saving because liquid table mode was selected but the liquid table was not imported.");
    }}
    if ("table".equals(REFRIGERANT_PROPERTY_WRITE_MODE) && vaporTable == null) {{
      throw new RuntimeException("[refprop-to-ccm] Stop saving because vapor table was not imported.");
    }}
    if (liquidMaterial != null) {{
      setLiquidProperties(liquidMaterial, liquidTable);
    }}
    if (vaporMaterial != null) {{
      setVaporProperties(vaporMaterial, vaporTable);
    }}
    writeLiquidValuesToLog();
    writeApplySummary();
    sim.println("[refprop-to-ccm] Vapor table path: " + VAPOR_TABLE);
    sim.println("[refprop-to-ccm] Saving simulation as: " + OUTPUT_SIM);
    sim.saveState(OUTPUT_SIM);
  }}

  private PhysicsContinuum getExistingContinuum() {{
    try {{
      Continuum continuum = sim.getContinuumManager().getContinuum(CONTINUUM_NAME);
      if (continuum == null) {{
        throw new RuntimeException("Continuum not found: " + CONTINUUM_NAME);
      }}
      sim.println("[refprop-to-ccm] Found continuum: " + continuum.getPresentationName());
      return (PhysicsContinuum) continuum;
    }} catch (Throwable ex) {{
      throw new RuntimeException("Could not find target physics continuum '" + CONTINUUM_NAME + "'. Check the GUI continuum name.", ex);
    }}
  }}

  private Material[] getExistingPhaseMaterials(PhysicsContinuum continuum) {{
    EulerianMultiPhaseModel multiphase = continuum.getModelManager().getModel(EulerianMultiPhaseModel.class);
    if (multiphase == null) {{
      throw new RuntimeException("Target continuum does not have EulerianMultiPhaseModel. Select an existing multiphase continuum.");
    }}

    EulerianPhase vaporPhase = getExistingPhase(multiphase, VAPOR_PHASE_NAME);
    EulerianPhase liquidPhase = getExistingPhase(multiphase, LIQUID_PHASE_NAME);

    Material vaporMaterial = getMaterialFromPhase(vaporPhase, Arrays.asList(
      "star.material.SinglePhaseGasModel",
      "star.material.SingleComponentGasModel"
    ), "gas");
    Material liquidMaterial = getMaterialFromPhase(liquidPhase, Arrays.asList(
      "star.material.SinglePhaseLiquidModel",
      "star.material.SingleComponentLiquidModel"
    ), "liquid");

    sim.println("[refprop-to-ccm] Found existing phase materials.");
    return new Material[] {{ liquidMaterial, vaporMaterial }};
  }}

  private EulerianPhase getExistingPhase(EulerianMultiPhaseModel multiphase, String phaseName) {{
    try {{
      Phase phase = multiphase.getPhaseManager().getPhase(phaseName);
      if (phase == null) {{
        throw new RuntimeException("Phase not found: " + phaseName);
      }}
      sim.println("[refprop-to-ccm] Found phase: " + phaseName);
      return (EulerianPhase) phase;
    }} catch (Throwable ex) {{
      throw new RuntimeException("Could not find phase '" + phaseName + "' in target continuum.", ex);
    }}
  }}

  private Material getMaterialFromPhase(EulerianPhase phase, List<String> materialModelClasses, String phaseLabel) {{
    for (String className : materialModelClasses) {{
      try {{
        Class modelClass = Class.forName(className);
        Object model = phase.getModelManager().getModel(modelClass);
        if (model != null) {{
          Material material = (Material) model.getClass().getMethod("getMaterial").invoke(model);
          sim.println("[refprop-to-ccm] Found " + phaseLabel + " material via " + className + ": " + material.getPresentationName());
          return material;
        }}
      }} catch (Throwable ex) {{
        sim.println("[refprop-to-ccm] Material model lookup skipped for " + phaseLabel + ": " + className + " -> " + ex.getMessage());
      }}
    }}
    throw new RuntimeException("No supported material model found on " + phaseLabel + " phase. Expected existing gas/liquid material model.");
  }}

  private Table importVaporTableBestEffort() {{
    if ("polynomial".equals(REFRIGERANT_PROPERTY_WRITE_MODE)) {{
      sim.println("[refprop-to-ccm] Refrigerant property write mode is polynomial; no vapor table import.");
      return null;
    }}
    try {{
      File tableFile = new File(VAPOR_TABLE);
      sim.println("[refprop-to-ccm] Table file exists: " + tableFile.exists());
      Table table = sim.getTableManager().createFromFile(VAPOR_TABLE);
      table.setPresentationName("REFPROP " + VAPOR_PHASE_NAME + " Temperature Table");
      sim.println("[refprop-to-ccm] Imported vapor table: " + table.getPresentationName());
      return table;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Table import check failed: " + ex.getMessage());
      return null;
    }}
  }}

  private Table importLiquidTableBestEffort() {{
    if (!"table".equals(LIQUID_PROPERTY_MODE)) {{
      sim.println("[refprop-to-ccm] Liquid property mode is saturation constants; no liquid table import.");
      return null;
    }}
    if ("polynomial".equals(REFRIGERANT_PROPERTY_WRITE_MODE)) {{
      sim.println("[refprop-to-ccm] Refrigerant property write mode is polynomial; no liquid table import.");
      return null;
    }}
    try {{
      File tableFile = new File(LIQUID_TABLE);
      sim.println("[refprop-to-ccm] Liquid table file exists: " + tableFile.exists());
      Table table = sim.getTableManager().createFromFile(LIQUID_TABLE);
      table.setPresentationName("REFPROP " + LIQUID_PHASE_NAME + " Temperature Table");
      sim.println("[refprop-to-ccm] Imported liquid table: " + table.getPresentationName());
      return table;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Liquid table import check failed: " + ex.getMessage());
      return null;
    }}
  }}

  private void setLiquidProperties(Material material, Table table) {{
    sim.println("[refprop-to-ccm] Applying liquid saturated constants to " + material.getPresentationName());
    setConstantWithUnitsOrDefault(material, "star.energy.SaturationTemperatureProperty", {saturation_temperature_c:.12g}, "C", {liquid.saturation_temperature_k:.12g}, "Saturation Temperature");
    setConstantWithUnitsOrDefault(material, "star.energy.SpecificHeatProperty", {liquid.specific_heat_j_per_kg_k:.12g}, "J/kg-K", {liquid.specific_heat_j_per_kg_k:.12g}, "Specific Heat");
    setConstantWithUnitsOrDefault(material, "star.energy.StandardStateTemperatureProperty", {standard_state_temperature_c:.12g}, "C", {liquid.standard_state_temperature_k:.12g}, "Standard State Temperature");
    setConstantWithUnitsOrDefault(material, "star.energy.ThermalConductivityProperty", {liquid.thermal_conductivity_w_per_m_k:.12g}, "W/m-K", {liquid.thermal_conductivity_w_per_m_k:.12g}, "Thermal Conductivity");
    setConstantWithUnitsOrDefault(material, "star.flow.DynamicViscosityProperty", {liquid.dynamic_viscosity_pa_s:.12g}, "Pa-s", {liquid.dynamic_viscosity_pa_s:.12g}, "Dynamic Viscosity");
    if (!setConstantWithUnitsOrDefault(material, "star.userdefinedeos.UserDefinedDensityProperty", {liquid.density_kg_per_m3:.12g}, "kg/m^3", {liquid.density_kg_per_m3:.12g}, "Liquid User-defined EOS Density", false)) {{
      if (!setConstantWithUnitsOrDefault(material, "star.energy.PolynomialDensityProperty", {liquid.density_kg_per_m3:.12g}, "kg/m^3", {liquid.density_kg_per_m3:.12g}, "Polynomial Density", false)) {{
        if (!setConstantWithUnitsOrDefault(material, "star.flow.ConstantDensityProperty", {liquid.density_kg_per_m3:.12g}, "kg/m^3", {liquid.density_kg_per_m3:.12g}, "Constant Density", false)) {{
          recordFailure("Density could not be set with any supported material property.");
        }}
      }}
    }}
    if (!setConstantWithUnitsOrDefault(material, "star.userdefinedeos.UserDefinedDrhoDTProperty", {liquid.density_temperature_derivative_kg_per_m3_k:.12g}, "kg/m^3-K", {liquid.density_temperature_derivative_kg_per_m3_k:.12g}, "Liquid Density Temperature Derivative", false)) {{
      if (Math.abs({liquid.density_temperature_derivative_kg_per_m3_k:.12g}) < 1.0e-20) {{
        recordSkipped("Liquid Density Temperature Derivative not available on target material; source value is 0 so it was skipped.");
      }} else {{
        recordFailure("Liquid Density Temperature Derivative could not be set because target material does not expose UserDefinedDrhoDTProperty.");
      }}
    }}
    setConstantWithUnitsOrDefault(material, "star.material.MolecularWeightProperty", {liquid.molecular_weight_kg_per_kmol:.12g}, "kg/kmol", {liquid.molecular_weight_kg_per_kmol:.12g}, "Molecular Weight");
    setConstantWithUnitsOrDefault(material, "star.energy.HeatOfFormationProperty", {liquid.liquid_standard_state_enthalpy_j_per_kg:.12g}, "J/kg", {liquid.liquid_standard_state_enthalpy_j_per_kg:.12g}, "Heat of Formation");
    if ("table".equals(LIQUID_PROPERTY_MODE) && (table != null || "polynomial".equals(REFRIGERANT_PROPERTY_WRITE_MODE))) {{
      sim.println("[refprop-to-ccm] Applying liquid temperature-dependent properties to " + material.getPresentationName());
{liquid_temperature_assignment}
    }}
  }}

  private void setVaporProperties(Material material, Table table) {{
    sim.println("[refprop-to-ccm] Applying vapor constants and temperature-dependent properties to " + material.getPresentationName());
    setConstantWithUnitsOrDefault(material, "star.energy.SaturationTemperatureProperty", {saturation_temperature_c:.12g}, "C", {liquid.saturation_temperature_k:.12g}, "Saturation Temperature");
    setConstantWithUnitsOrDefault(material, "star.energy.StandardStateTemperatureProperty", {standard_state_temperature_c:.12g}, "C", {liquid.standard_state_temperature_k:.12g}, "Standard State Temperature");
{vapor_entropy_assignment.rstrip()}
    setConstantWithUnitsOrDefault(material, "star.material.MolecularWeightProperty", {liquid.molecular_weight_kg_per_kmol:.12g}, "kg/kmol", {liquid.molecular_weight_kg_per_kmol:.12g}, "Molecular Weight");
    if (!setConstantWithUnitsOrDefault(material, "star.userdefinedeos.UserDefinedDrhoDTProperty", {liquid.density_temperature_derivative_kg_per_m3_k:.12g}, "kg/m^3-K", {liquid.density_temperature_derivative_kg_per_m3_k:.12g}, "Density Temperature Derivative", false)) {{
      if (Math.abs({liquid.density_temperature_derivative_kg_per_m3_k:.12g}) < 1.0e-20) {{
        recordSkipped("Density Temperature Derivative not available on target vapor material; source value is 0 so it was skipped.");
      }} else {{
        recordFailure("Density Temperature Derivative could not be set because target vapor material does not expose UserDefinedDrhoDTProperty.");
      }}
    }}
    setConstantWithUnitsOrDefault(material, "star.energy.HeatOfFormationProperty", {liquid.vapor_standard_state_enthalpy_j_per_kg:.12g}, "J/kg", {liquid.vapor_standard_state_enthalpy_j_per_kg:.12g}, "Heat of Formation");
{vapor_temperature_assignment}
  }}

  private void setLiquidTemperatureTables(Material material, Table table) {{
    setTemperatureTable(material, table, "star.energy.SpecificHeatProperty", "star.energy.SpecificHeatTemperatureTable", "Equivalent Specific Heat", "Equivalent Specific Heat", "Liquid Specific Heat");
    if (!setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedDensityProperty", "star.energy.TemperatureTableMethod", "Density", "Density", "Liquid User-defined EOS Density", false)) {{
      if (!setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.DensityTemperatureTableDT", "Density", "Density", "Liquid Density", false)) {{
        if (!setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.TemperatureTableMethod", "Density", "Density", "Liquid Density", false)) {{
          if (!setTemperatureTable(material, table, "star.flow.ConstantDensityProperty", "star.energy.DensityTemperatureTableDT", "Density", "Density", "Liquid Constant Density fallback", false)) {{
            recordFailure("Liquid Density table could not be bound; target liquid material does not expose a supported density table method.");
          }}
        }}
      }}
    }}
    if (!setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedEnthalpyProperty", "star.energy.EnthalpyTemperatureTable", "Enthalpy", "Enthalpy", "Liquid User-defined EOS Enthalpy", false)) {{
      recordFailure("Liquid User-defined EOS Enthalpy table could not be bound; target liquid material does not expose UserDefinedEnthalpyProperty.");
    }}
    setTemperatureTable(material, table, "star.energy.ThermalConductivityProperty", "star.energy.TemperatureTableMethod", "Equivalent Thermal Conductivity", "Equivalent Thermal Conductivity", "Liquid Thermal Conductivity");
    setTemperatureTable(material, table, "star.flow.DynamicViscosityProperty", "star.energy.TemperatureTableMethod", "Equivalent Dynamic Viscosity", "Equivalent Dynamic Viscosity", "Liquid Dynamic Viscosity");
  }}

  private void setLiquidTemperaturePolynomials(Material material) {{
    setTemperaturePolynomial(material, "star.energy.SpecificHeatProperty", new String[]{{"star.energy.PolynomialSpecificHeat", "star.energy.TemperaturePolynomial"}}, LIQUID_SPECIFIC_HEAT_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "J/kg-K", "Liquid Specific Heat polynomial");
    if (!setTemperaturePolynomial(material, "star.userdefinedeos.UserDefinedDensityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, LIQUID_DENSITY_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "kg/m^3", "Liquid User-defined EOS Density polynomial", false)) {{
      if (!setTemperaturePolynomial(material, "star.energy.PolynomialDensityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, LIQUID_DENSITY_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "kg/m^3", "Liquid Density polynomial", false)) {{
        recordFailure("Liquid Density polynomial could not be bound; target liquid material does not expose a supported polynomial method.");
      }}
    }}
    if (!setTemperaturePolynomial(material, "star.userdefinedeos.UserDefinedEnthalpyProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, LIQUID_ENTHALPY_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "J/kg", "Liquid User-defined EOS Enthalpy polynomial", false)) {{
      recordFailure("Liquid User-defined EOS Enthalpy polynomial could not be bound; target liquid material does not expose UserDefinedEnthalpyProperty.");
    }}
    setTemperaturePolynomial(material, "star.energy.ThermalConductivityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, LIQUID_THERMAL_CONDUCTIVITY_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "W/m-K", "Liquid Thermal Conductivity polynomial");
    setTemperaturePolynomial(material, "star.flow.DynamicViscosityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, LIQUID_DYNAMIC_VISCOSITY_POLY, LIQUID_T_MIN_C, LIQUID_T_MAX_C, "C", "Pa-s", "Liquid Dynamic Viscosity polynomial");
  }}

  private void setVaporTemperatureTables(Material material, Table table) {{
    if (!setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedDensityProperty", "star.energy.TemperatureTableMethod", "Density", "Density", "User-defined EOS Density", false)) {{
      if (!setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.DensityTemperatureTableDT", "Density", "Density", "Density", false)) {{
        if (!setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.TemperatureTableMethod", "Density", "Density", "Density", false)) {{
          if (!setTemperatureTable(material, table, "star.flow.ConstantDensityProperty", "star.energy.DensityTemperatureTableDT", "Density", "Density", "Constant Density fallback", false)) {{
            recordFailure("Vapor Density table could not be bound; target vapor material does not expose a supported density table method.");
          }}
        }}
      }}
    }}
    setVaporEnthalpyAndSpecificHeat(material, table);
    setTemperatureTable(material, table, "star.energy.ThermalConductivityProperty", "star.energy.TemperatureTableMethod", "Equivalent Thermal Conductivity", "Equivalent Thermal Conductivity", "Thermal Conductivity");
    setTemperatureTable(material, table, "star.flow.DynamicViscosityProperty", "star.energy.TemperatureTableMethod", "Equivalent Dynamic Viscosity", "Equivalent Dynamic Viscosity", "Dynamic Viscosity");
  }}

  private void setVaporTemperaturePolynomials(Material material) {{
    if (!setTemperaturePolynomial(material, "star.userdefinedeos.UserDefinedDensityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, VAPOR_DENSITY_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "kg/m^3", "User-defined EOS Density polynomial", false)) {{
      if (!setTemperaturePolynomial(material, "star.energy.PolynomialDensityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, VAPOR_DENSITY_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "kg/m^3", "Density polynomial", false)) {{
        recordFailure("Vapor Density polynomial could not be bound; target vapor material does not expose a supported polynomial method.");
      }}
    }}
    setVaporEnthalpyAndSpecificHeatPolynomial(material);
    setTemperaturePolynomial(material, "star.energy.ThermalConductivityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, VAPOR_THERMAL_CONDUCTIVITY_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "W/m-K", "Thermal Conductivity polynomial");
    setTemperaturePolynomial(material, "star.flow.DynamicViscosityProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, VAPOR_DYNAMIC_VISCOSITY_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "Pa-s", "Dynamic Viscosity polynomial");
  }}

  private void setVaporEnthalpyAndSpecificHeat(Material material, Table table) {{
    boolean enthalpyBound = setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedEnthalpyProperty", "star.energy.EnthalpyTemperatureTable", "Enthalpy", "Enthalpy", "User-defined EOS Enthalpy", false);
    if ("enthalpy_table".equals(VAPOR_SPECIFIC_HEAT_SOURCE)) {{
      if (enthalpyBound) {{
        sim.println("[refprop-to-ccm] Using user-defined EOS enthalpy table as vapor specific heat source.");
      }} else {{
        recordFailure("User-defined EOS Enthalpy table could not be bound; target vapor material does not expose UserDefinedEnthalpyProperty.");
      }}
      return;
    }}
    if (!setTemperatureTable(material, table, "star.energy.SpecificHeatProperty", "star.userdefinedeos.UserDefinedSpecificHeatTemperatureTable", "Equivalent Specific Heat", "Equivalent Specific Heat", "User-defined EOS Specific Heat Cp(T)", false)) {{
      if (!setTemperatureTable(material, table, "star.energy.SpecificHeatProperty", "star.energy.SpecificHeatTemperatureTable", "Equivalent Specific Heat", "Equivalent Specific Heat", "Specific Heat Cp(T)", false)) {{
        recordFailure("Vapor Specific Heat Cp(T) table could not be bound; target vapor material does not expose a supported specific heat table method.");
      }}
    }}
  }}

  private void setVaporEnthalpyAndSpecificHeatPolynomial(Material material) {{
    boolean enthalpyBound = setTemperaturePolynomial(material, "star.userdefinedeos.UserDefinedEnthalpyProperty", new String[]{{"star.energy.TemperaturePolynomial"}}, VAPOR_ENTHALPY_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "J/kg", "User-defined EOS Enthalpy polynomial", false);
    if ("enthalpy_table".equals(VAPOR_SPECIFIC_HEAT_SOURCE)) {{
      if (enthalpyBound) {{
        sim.println("[refprop-to-ccm] Using user-defined EOS enthalpy polynomial as vapor specific heat source.");
      }} else {{
        recordFailure("User-defined EOS Enthalpy polynomial could not be bound; target vapor material does not expose UserDefinedEnthalpyProperty.");
      }}
      return;
    }}
    if (!setTemperaturePolynomial(material, "star.energy.SpecificHeatProperty", new String[]{{"star.energy.PolynomialSpecificHeat", "star.energy.TemperaturePolynomial"}}, VAPOR_SPECIFIC_HEAT_POLY, VAPOR_T_MIN_C, VAPOR_T_MAX_C, "C", "J/kg-K", "User-defined EOS Specific Heat Cp(T) polynomial", false)) {{
      recordFailure("Vapor Specific Heat Cp(T) polynomial could not be bound; target vapor material does not expose a supported specific heat polynomial method.");
    }}
  }}

  private boolean setConstantWithUnitsOrDefault(Material material, String propertyClassName, double value, String unitName, double defaultUnitValue, String label) {{
    return setConstantWithUnitsOrDefault(material, propertyClassName, value, unitName, defaultUnitValue, label, true);
  }}

  private boolean setConstantWithUnitsOrDefault(Material material, String propertyClassName, double value, String unitName, double defaultUnitValue, String label, boolean recordFailureOnError) {{
    try {{
      Class propertyClass = Class.forName(propertyClassName);
      MaterialProperty property = (MaterialProperty) material.getMaterialProperties().getMaterialProperty(propertyClass);
      property.setConstant(defaultUnitValue);
      MaterialPropertyMethod method = property.getMethod();
      Object quantity = method.getClass().getMethod("getQuantity").invoke(method);
      try {{
        Units units = (Units) sim.getUnitsManager().getObject(unitName);
        quantity.getClass().getMethod("setValueAndUnits", double.class, Units.class).invoke(quantity, value, units);
        recordSuccess(label + " = " + value + " " + unitName + " (explicit unit)");
        return true;
      }} catch (Throwable unitEx) {{
        sim.println("[refprop-to-ccm] Explicit unit write failed for " + label + " via " + propertyClassName + "; trying fallback default-unit numeric value = " + defaultUnitValue + ": " + unitEx.getMessage());
      }}
      quantity.getClass().getMethod("setValue", double.class).invoke(quantity, defaultUnitValue);
      recordSuccess(label + " = " + defaultUnitValue + " (fallback default-unit numeric value; source " + value + " " + unitName + ")");
      return true;
    }} catch (Throwable ex) {{
      if (recordFailureOnError) {{
        recordFailure(label + " via " + propertyClassName + ": " + ex.getMessage());
      }} else {{
        sim.println("[refprop-to-ccm] Candidate constant write skipped for " + label + " via " + propertyClassName + ": " + ex.getMessage());
      }}
      return false;
    }}
  }}

  private boolean setTemperaturePolynomial(Material material, String propertyClassName, String[] methodClassNames, double[] coefficients, double minTemperatureC, double maxTemperatureC, String inputUnitName, String outputUnitName, String label) {{
    return setTemperaturePolynomial(material, propertyClassName, methodClassNames, coefficients, minTemperatureC, maxTemperatureC, inputUnitName, outputUnitName, label, true);
  }}

  private boolean setTemperaturePolynomial(Material material, String propertyClassName, String[] methodClassNames, double[] coefficients, double minTemperatureC, double maxTemperatureC, String inputUnitName, String outputUnitName, String label, boolean recordFailureOnError) {{
    if (coefficients.length == 0) {{
      if (recordFailureOnError) {{
        recordFailure(label + ": no polynomial coefficients were generated.");
      }}
      return false;
    }}
    for (String methodClassName : methodClassNames) {{
      try {{
        Class propertyClass = Class.forName(propertyClassName);
        Class methodClass = Class.forName(methodClassName);
        MaterialProperty property = (MaterialProperty) material.getMaterialProperties().getMaterialProperty(propertyClass);
        property.setMethod(methodClass);
        MaterialPropertyMethod method = property.getMethod();
        Object polynomial = method.getClass().getMethod("getPolynomial").invoke(method);
        configurePolynomial(polynomial, coefficients, minTemperatureC, maxTemperatureC, inputUnitName, outputUnitName);
        recordSuccess("Bound " + label + " via " + propertyClassName + " / " + methodClassName + " degree=" + (coefficients.length - 1));
        return true;
      }} catch (Throwable ex) {{
        sim.println("[refprop-to-ccm] Candidate polynomial binding skipped for " + label + " via " + propertyClassName + " / " + methodClassName + ": " + ex.getMessage());
      }}
    }}
    if (recordFailureOnError) {{
      recordFailure("Could not bind " + label + " polynomial via " + propertyClassName + ".");
    }}
    return false;
  }}

  private void configurePolynomial(Object polynomial, double[] coefficients, double minTemperatureC, double maxTemperatureC, String inputUnitName, String outputUnitName) throws Exception {{
    polynomial.getClass().getMethod("setNumberOfIntervals", int.class).invoke(polynomial, 1);
    polynomial.getClass().getMethod("setIntervalRanges", DoubleVector.class).invoke(polynomial, new DoubleVector(new double[]{{minTemperatureC, maxTemperatureC}}));
    polynomial.getClass().getMethod("setNumberOfCoefficients", IntVector.class).invoke(polynomial, new IntVector(new int[]{{coefficients.length}}));
    polynomial.getClass().getMethod("setCoefficients", DoubleVector.class).invoke(polynomial, new DoubleVector(coefficients));
    try {{
      polynomial.getClass().getMethod("setUseRealExponents", boolean.class).invoke(polynomial, false);
      double[] exponents = new double[coefficients.length];
      for (int i = 0; i < coefficients.length; i++) {{
        exponents[i] = i;
      }}
      polynomial.getClass().getMethod("setExponents", DoubleVector.class).invoke(polynomial, new DoubleVector(exponents));
    }} catch (Throwable exponentEx) {{
      sim.println("[refprop-to-ccm] Polynomial exponent setup skipped: " + exponentEx.getMessage());
    }}
    try {{
      polynomial.getClass().getMethod("setInputUnits", Units.class).invoke(polynomial, (Units) sim.getUnitsManager().getObject(inputUnitName));
      polynomial.getClass().getMethod("setOutputUnits", Units.class).invoke(polynomial, (Units) sim.getUnitsManager().getObject(outputUnitName));
    }} catch (Throwable unitEx) {{
      sim.println("[refprop-to-ccm] Polynomial explicit unit setup skipped for " + inputUnitName + " -> " + outputUnitName + ": " + unitEx.getMessage());
    }}
  }}

  private boolean setTemperatureTable(Material material, Table table, String propertyClassName, String methodClassName, String dataColumn, String fallbackDataColumn, String label) {{
    return setTemperatureTable(material, table, propertyClassName, methodClassName, dataColumn, fallbackDataColumn, label, true);
  }}

  private boolean setTemperatureTable(Material material, Table table, String propertyClassName, String methodClassName, String dataColumn, String fallbackDataColumn, String label, boolean recordFailureOnError) {{
    try {{
      Class propertyClass = Class.forName(propertyClassName);
      Class methodClass = Class.forName(methodClassName);
      MaterialProperty property = (MaterialProperty) material.getMaterialProperties().getMaterialProperty(propertyClass);
      property.setMethod(methodClass);
      MaterialPropertyMethod method = property.getMethod();
      Object interpolation = method.getClass().getMethod("getInterpolationTable").invoke(method);
      interpolation.getClass().getMethod("setTable", Table.class).invoke(interpolation, table);
      setTableColumn(interpolation, "setT", "Temperature", "Temperature", "Temperature");
      setTableColumn(interpolation, "setData", dataColumn, fallbackDataColumn, label);
      recordSuccess("Bound " + label + " to table column: " + dataColumn + " / " + fallbackDataColumn);
      return true;
    }} catch (Throwable ex) {{
      if (recordFailureOnError) {{
        recordFailure("Could not bind " + label + " table via " + propertyClassName + " / " + methodClassName + ": " + ex.getMessage());
      }} else {{
        sim.println("[refprop-to-ccm] Candidate table binding skipped for " + label + " via " + propertyClassName + " / " + methodClassName + ": " + ex.getMessage());
      }}
      return false;
    }}
  }}

  private void recordSuccess(String detail) {{
    successfulWrites.add(detail);
    sim.println("[refprop-to-ccm] SUCCESS: " + detail);
  }}

  private void recordFailure(String detail) {{
    failedWrites.add(detail);
    sim.println("[refprop-to-ccm] FAILED: " + detail);
  }}

  private void recordSkipped(String detail) {{
    skippedWrites.add(detail);
    sim.println("[refprop-to-ccm] SKIPPED: " + detail);
  }}

  private void writeApplySummary() {{
    sim.println("[refprop-to-ccm] Apply summary: succeeded=" + successfulWrites.size() + ", failed=" + failedWrites.size() + ", skipped=" + skippedWrites.size());
    for (String detail : successfulWrites) {{
      sim.println("[refprop-to-ccm]   SUCCESS: " + detail);
    }}
    for (String detail : failedWrites) {{
      sim.println("[refprop-to-ccm]   FAILED: " + detail);
    }}
    for (String detail : skippedWrites) {{
      sim.println("[refprop-to-ccm]   SKIPPED: " + detail);
    }}
  }}

  private void setTableColumn(Object interpolation, String setterName, String preferred, String fallback, String label) throws Exception {{
    try {{
      interpolation.getClass().getMethod(setterName, String.class).invoke(interpolation, preferred);
    }} catch (Throwable preferredEx) {{
      sim.println("[refprop-to-ccm] Preferred table column failed for " + label + ": " + preferred + " -> " + preferredEx.getMessage());
      interpolation.getClass().getMethod(setterName, String.class).invoke(interpolation, fallback);
    }}
  }}

  private void writeLiquidValuesToLog() {{
    sim.println("[refprop-to-ccm] Liquid saturated properties:");
    sim.println("  Liquid Property Mode = " + LIQUID_PROPERTY_MODE);
    sim.println("  Liquid table path = " + LIQUID_TABLE);
    sim.println("  Saturation Temperature C applied to STAR = {saturation_temperature_c:.12g}");
    sim.println("  Saturation Pressure Pa = {liquid.saturation_pressure_pa:.12g}");
    sim.println("  Specific Heat J/kg-K = {liquid.specific_heat_j_per_kg_k:.12g}");
    sim.println("  Standard State Temperature C applied to STAR = {standard_state_temperature_c:.12g}");
    sim.println("  Thermal Conductivity W/m-K = {liquid.thermal_conductivity_w_per_m_k:.12g}");
    sim.println("  Dynamic Viscosity Pa-s = {liquid.dynamic_viscosity_pa_s:.12g}");
    sim.println("  Density kg/m3 = {liquid.density_kg_per_m3:.12g}");
    sim.println("  Molecular Weight kg/kmol = {liquid.molecular_weight_kg_per_kmol:.12g}");
    sim.println("  Saturated Liquid Enthalpy J/kg = {liquid.saturated_liquid_enthalpy_j_per_kg:.12g}");
    sim.println("  Saturated Vapor Enthalpy J/kg = {liquid.saturated_vapor_enthalpy_j_per_kg:.12g}");
    sim.println("  Liquid Standard State Enthalpy / Heat of Formation input J/kg = {liquid.liquid_standard_state_enthalpy_j_per_kg:.12g}");
    sim.println("  Vapor Standard State Enthalpy / Heat of Formation input J/kg = {liquid.vapor_standard_state_enthalpy_j_per_kg:.12g}");
{vapor_entropy_log}
    sim.println("  Density Temperature Derivative kg/m3-K = {liquid.density_temperature_derivative_kg_per_m3_k:.12g}");
    sim.println("  Vapor Specific Heat Source = " + VAPOR_SPECIFIC_HEAT_SOURCE);
  }}
}}
"""


def _fit_property_polynomials(path: Path, degree: int) -> PropertyPolynomials:
    rows = _read_property_rows(path)
    if not rows:
        raise ValueError(f"No property rows found in {path}")

    temperatures = np.array([row["temperature"] for row in rows], dtype=float)
    effective_degree = min(max(0, int(degree)), max(len(temperatures) - 1, 0))

    def fit(column: str) -> tuple[float, ...]:
        values = np.array([row[column] for row in rows], dtype=float)
        if not np.all(np.isfinite(values)):
            raise ValueError(f"Non-finite values found in {path} column {PROPERTY_CSV_COLUMNS[column]}")
        coefficients = np.polynomial.polynomial.polyfit(temperatures, values, effective_degree)
        return tuple(float(value) for value in coefficients)

    return PropertyPolynomials(
        temperature_min_c=float(np.min(temperatures)),
        temperature_max_c=float(np.max(temperatures)),
        density=fit("density"),
        specific_heat=fit("specific_heat"),
        thermal_conductivity=fit("thermal_conductivity"),
        dynamic_viscosity=fit("dynamic_viscosity"),
        enthalpy=fit("enthalpy"),
    )


def _read_property_rows(path: Path) -> list[dict[str, float]]:
    rows: list[dict[str, float]] = []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        missing = [column for column in PROPERTY_CSV_COLUMNS.values() if column not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"Missing required REFPROP CSV columns in {path}: {', '.join(missing)}")
        for row in reader:
            parsed = {
                key: float(row[column_name])
                for key, column_name in PROPERTY_CSV_COLUMNS.items()
            }
            if not all(np.isfinite(value) for value in parsed.values()):
                raise ValueError(f"Non-finite property row found in {path}")
            rows.append(parsed)
    return rows


def _java_polynomial_constants(prefix: str, polynomials: PropertyPolynomials | None) -> str:
    if polynomials is None:
        polynomials = PropertyPolynomials(
            temperature_min_c=0.0,
            temperature_max_c=0.0,
            density=(),
            specific_heat=(),
            thermal_conductivity=(),
            dynamic_viscosity=(),
            enthalpy=(),
        )
    return "\n".join(
        [
            f"  private static final double {prefix}_T_MIN_C = {_java_number(polynomials.temperature_min_c)};",
            f"  private static final double {prefix}_T_MAX_C = {_java_number(polynomials.temperature_max_c)};",
            f"  private static final double[] {prefix}_DENSITY_POLY = {_java_double_array(polynomials.density)};",
            f"  private static final double[] {prefix}_SPECIFIC_HEAT_POLY = {_java_double_array(polynomials.specific_heat)};",
            (
                f"  private static final double[] {prefix}_THERMAL_CONDUCTIVITY_POLY = "
                f"{_java_double_array(polynomials.thermal_conductivity)};"
            ),
            f"  private static final double[] {prefix}_DYNAMIC_VISCOSITY_POLY = {_java_double_array(polynomials.dynamic_viscosity)};",
            f"  private static final double[] {prefix}_ENTHALPY_POLY = {_java_double_array(polynomials.enthalpy)};",
        ]
    )


def _java_double_array(values: tuple[float, ...]) -> str:
    return "new double[] {" + ", ".join(_java_number(value) for value in values) + "}"


def _java_number(value: float) -> str:
    return f"{value:.17g}"


class StarCcmRunner:
    def __init__(self, config: ToolConfig) -> None:
        self.config = config

    def run(self, macro_file: Path) -> Path:
        if self.config.starccm_exe is None:
            raise ValueError("starccm.starccm_exe is required unless --no-run-star is used.")
        if not self.config.starccm_exe.exists():
            raise FileNotFoundError(f"STAR-CCM+ executable does not exist: {self.config.starccm_exe}")
        if not self.config.sim_file.exists():
            raise FileNotFoundError(f"STAR-CCM+ sim file does not exist: {self.config.sim_file}")

        command = [
            str(self.config.starccm_exe),
            "-batch",
            str(macro_file),
            str(self.config.sim_file),
        ]
        log_file = self.config.output_directory / "starccm_run.log"
        with log_file.open("w", encoding="utf-8", errors="replace") as handle:
            handle.write("Command:\n")
            handle.write(" ".join(command))
            handle.write("\n\nOutput:\n")
            try:
                completed = subprocess.run(
                    command,
                    stdout=handle,
                    stderr=subprocess.STDOUT,
                    text=True,
                    check=False,
                    timeout=STARCCM_RUN_TIMEOUT_SECONDS,
                )
            except subprocess.TimeoutExpired as exc:
                handle.write(f"\nSTAR-CCM+ run timed out after {STARCCM_RUN_TIMEOUT_SECONDS} seconds.\n")
                raise TimeoutError(
                    f"STAR-CCM+ 运行超时（超过 {STARCCM_RUN_TIMEOUT_SECONDS} 秒）。"
                    f"日志: {log_file.resolve()}"
                ) from exc
        if completed.returncode != 0:
            raise RuntimeError(f"STAR-CCM+ run failed with exit code {completed.returncode}. Log: {log_file.resolve()}")
        return log_file.resolve()


def _java(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
