from __future__ import annotations

import subprocess
from pathlib import Path

from .config import ToolConfig
from .models import LiquidProperties


def render_macro(
    config: ToolConfig,
    liquid: LiquidProperties,
    liquid_csv: Path | None,
    vapor_csv: Path,
    output_sim: Path,
) -> str:
    liquid_table_path = str(liquid_csv) if liquid_csv is not None else ""
    return f"""// Auto-generated by refprop-to-ccm. Edit the property mapping section if STAR-CCM+ reports missing paths.
package macro;

import java.io.File;
import java.util.Arrays;
import java.util.List;

import star.common.*;
import star.base.neo.*;
import star.material.*;

public class apply_refprop_to_star extends StarMacro {{
  private Simulation sim;

  private static final String CONTINUUM_NAME = "{_java(config.continuum_name)}";
  private static final String LIQUID_PHASE_NAME = "{_java(config.liquid_phase_name)}";
  private static final String VAPOR_PHASE_NAME = "{_java(config.vapor_phase_name)}";
  private static final String VAPOR_SPECIFIC_HEAT_SOURCE = "{_java(config.vapor_specific_heat_source)}";
  private static final String LIQUID_PROPERTY_MODE = "{_java(config.liquid_property_mode)}";
  private static final String LIQUID_TABLE = "{_java(liquid_table_path)}";
  private static final String VAPOR_TABLE = "{_java(str(vapor_csv))}";
  private static final String OUTPUT_SIM = "{_java(str(output_sim))}";

  public void execute() {{
    sim = getActiveSimulation();
    sim.println("[refprop-to-ccm] Using existing continuum: " + CONTINUUM_NAME);
    PhysicsContinuum continuum = getExistingContinuum();

    Material liquidMaterial = null;
    Material vaporMaterial = null;
    try {{
      Material[] materials = getExistingPhaseMaterials(continuum);
      liquidMaterial = materials[0];
      vaporMaterial = materials[1];
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Existing phase/material lookup failed: " + ex.getMessage());
      throw new RuntimeException("[refprop-to-ccm] Stop saving because target continuum/phase/material lookup failed.", ex);
    }}
    Table liquidTable = importLiquidTableBestEffort();
    Table vaporTable = importVaporTableBestEffort();
    if ("table".equals(LIQUID_PROPERTY_MODE) && liquidTable == null) {{
      throw new RuntimeException("[refprop-to-ccm] Stop saving because liquid table mode was selected but the liquid table was not imported.");
    }}
    if (vaporTable == null) {{
      throw new RuntimeException("[refprop-to-ccm] Stop saving because vapor table was not imported.");
    }}
    if (liquidMaterial != null) {{
      setLiquidProperties(liquidMaterial, liquidTable);
    }}
    if (vaporMaterial != null) {{
      setVaporProperties(vaporMaterial, vaporTable);
    }}
    writeLiquidValuesToLog();
    sim.println("[refprop-to-ccm] Vapor table path: " + VAPOR_TABLE);
    sim.println("[refprop-to-ccm] Saving simulation as: " + OUTPUT_SIM);
    sim.saveState(OUTPUT_SIM);
  }}

  private PhysicsContinuum getExistingContinuum() {{
    try {{
      Continuum continuum = sim.getContinuumManager().getContinuum(CONTINUUM_NAME);
      if (continuum == null) {{
        throw new RuntimeException("Continuum not found: " + CONTINUUM_NAME);
      }}
      sim.println("[refprop-to-ccm] Found continuum: " + continuum.getPresentationName());
      return (PhysicsContinuum) continuum;
    }} catch (Throwable ex) {{
      throw new RuntimeException("Could not find target physics continuum '" + CONTINUUM_NAME + "'. Check the GUI continuum name.", ex);
    }}
  }}

  private Material[] getExistingPhaseMaterials(PhysicsContinuum continuum) {{
    EulerianMultiPhaseModel multiphase = continuum.getModelManager().getModel(EulerianMultiPhaseModel.class);
    if (multiphase == null) {{
      throw new RuntimeException("Target continuum does not have EulerianMultiPhaseModel. Select an existing multiphase continuum.");
    }}

    EulerianPhase vaporPhase = getExistingPhase(multiphase, VAPOR_PHASE_NAME);
    EulerianPhase liquidPhase = getExistingPhase(multiphase, LIQUID_PHASE_NAME);

    Material vaporMaterial = getMaterialFromPhase(vaporPhase, Arrays.asList(
      "star.material.SinglePhaseGasModel",
      "star.material.SingleComponentGasModel"
    ), "gas");
    Material liquidMaterial = getMaterialFromPhase(liquidPhase, Arrays.asList(
      "star.material.SinglePhaseLiquidModel",
      "star.material.SingleComponentLiquidModel"
    ), "liquid");

    sim.println("[refprop-to-ccm] Found existing phase materials.");
    return new Material[] {{ liquidMaterial, vaporMaterial }};
  }}

  private EulerianPhase getExistingPhase(EulerianMultiPhaseModel multiphase, String phaseName) {{
    try {{
      Phase phase = multiphase.getPhaseManager().getPhase(phaseName);
      if (phase == null) {{
        throw new RuntimeException("Phase not found: " + phaseName);
      }}
      sim.println("[refprop-to-ccm] Found phase: " + phaseName);
      return (EulerianPhase) phase;
    }} catch (Throwable ex) {{
      throw new RuntimeException("Could not find phase '" + phaseName + "' in target continuum.", ex);
    }}
  }}

  private Material getMaterialFromPhase(EulerianPhase phase, List<String> materialModelClasses, String phaseLabel) {{
    for (String className : materialModelClasses) {{
      try {{
        Class modelClass = Class.forName(className);
        Object model = phase.getModelManager().getModel(modelClass);
        if (model != null) {{
          Material material = (Material) model.getClass().getMethod("getMaterial").invoke(model);
          sim.println("[refprop-to-ccm] Found " + phaseLabel + " material via " + className + ": " + material.getPresentationName());
          return material;
        }}
      }} catch (Throwable ex) {{
        sim.println("[refprop-to-ccm] Material model lookup skipped for " + phaseLabel + ": " + className + " -> " + ex.getMessage());
      }}
    }}
    throw new RuntimeException("No supported material model found on " + phaseLabel + " phase. Expected existing gas/liquid material model.");
  }}

  private Table importVaporTableBestEffort() {{
    try {{
      File tableFile = new File(VAPOR_TABLE);
      sim.println("[refprop-to-ccm] Table file exists: " + tableFile.exists());
      Table table = sim.getTableManager().createFromFile(VAPOR_TABLE);
      table.setPresentationName("REFPROP " + VAPOR_PHASE_NAME + " Temperature Table");
      sim.println("[refprop-to-ccm] Imported vapor table: " + table.getPresentationName());
      return table;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Table import check failed: " + ex.getMessage());
      return null;
    }}
  }}

  private Table importLiquidTableBestEffort() {{
    if (!"table".equals(LIQUID_PROPERTY_MODE)) {{
      sim.println("[refprop-to-ccm] Liquid property mode is saturation constants; no liquid table import.");
      return null;
    }}
    try {{
      File tableFile = new File(LIQUID_TABLE);
      sim.println("[refprop-to-ccm] Liquid table file exists: " + tableFile.exists());
      Table table = sim.getTableManager().createFromFile(LIQUID_TABLE);
      table.setPresentationName("REFPROP " + LIQUID_PHASE_NAME + " Temperature Table");
      sim.println("[refprop-to-ccm] Imported liquid table: " + table.getPresentationName());
      return table;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Liquid table import check failed: " + ex.getMessage());
      return null;
    }}
  }}

  private void setLiquidProperties(Material material, Table table) {{
    sim.println("[refprop-to-ccm] Applying liquid saturated constants to " + material.getPresentationName());
    setConstant(material, "star.energy.SaturationTemperatureProperty", {liquid.saturation_temperature_k:.12g}, "Saturation Temperature");
    setConstant(material, "star.energy.SpecificHeatProperty", {liquid.specific_heat_j_per_kg_k:.12g}, "Specific Heat");
    setConstant(material, "star.energy.StandardStateTemperatureProperty", {liquid.standard_state_temperature_k:.12g}, "Standard State Temperature");
    setConstant(material, "star.energy.ThermalConductivityProperty", {liquid.thermal_conductivity_w_per_m_k:.12g}, "Thermal Conductivity");
    setConstant(material, "star.flow.DynamicViscosityProperty", {liquid.dynamic_viscosity_pa_s:.12g}, "Dynamic Viscosity");
    if (!setConstant(material, "star.energy.PolynomialDensityProperty", {liquid.density_kg_per_m3:.12g}, "Polynomial Density")) {{
      setConstant(material, "star.flow.ConstantDensityProperty", {liquid.density_kg_per_m3:.12g}, "Constant Density");
    }}
    setConstant(material, "star.material.MolecularWeightProperty", {liquid.molecular_weight_kg_per_kmol:.12g}, "Molecular Weight");
    setConstant(material, "star.energy.HeatOfFormationProperty", {liquid.liquid_standard_state_enthalpy_j_per_kg:.12g}, "Standard State Enthalpy / Heat of Formation input");
    if ("table".equals(LIQUID_PROPERTY_MODE) && table != null) {{
      sim.println("[refprop-to-ccm] Applying liquid temperature table to " + material.getPresentationName());
      setTemperatureTable(material, table, "star.energy.SpecificHeatProperty", "star.energy.SpecificHeatTemperatureTable", "Equivalent Specific Heat (J/kg-K)", "Equivalent Specific Heat", "Liquid Specific Heat");
      if (!setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.DensityTemperatureTableDT", "Density (kg/m3)", "Density", "Liquid Density")) {{
        setTemperatureTable(material, table, "star.flow.ConstantDensityProperty", "star.energy.DensityTemperatureTableDT", "Density (kg/m3)", "Density", "Liquid Constant Density fallback");
      }}
      setTemperatureTable(material, table, "star.energy.ThermalConductivityProperty", "star.energy.TemperatureTableMethod", "Equivalent Thermal Conductivity (W/m-K)", "Equivalent Thermal Conductivity", "Liquid Thermal Conductivity");
      setTemperatureTable(material, table, "star.flow.DynamicViscosityProperty", "star.energy.TemperatureTableMethod", "Equivalent Dynamic Viscosity (Pa-s)", "Equivalent Dynamic Viscosity", "Liquid Dynamic Viscosity");
    }}
  }}

  private void setVaporProperties(Material material, Table table) {{
    sim.println("[refprop-to-ccm] Applying vapor constants and temperature tables to " + material.getPresentationName());
    setConstant(material, "star.energy.SaturationTemperatureProperty", {liquid.saturation_temperature_k:.12g}, "Saturation Temperature");
    setConstant(material, "star.energy.StandardStateTemperatureProperty", {liquid.standard_state_temperature_k:.12g}, "Standard State Temperature");
    setConstant(material, "star.material.MolecularWeightProperty", {liquid.molecular_weight_kg_per_kmol:.12g}, "Molecular Weight");
    setConstant(material, "star.userdefinedeos.UserDefinedDrhoDTProperty", {liquid.density_temperature_derivative_kg_per_m3_k:.12g}, "Density Temperature Derivative");
    setConstant(material, "star.energy.HeatOfFormationProperty", {liquid.vapor_standard_state_enthalpy_j_per_kg:.12g}, "Standard State Enthalpy / Heat of Formation input");

    setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedDensityProperty", "star.energy.TemperatureTableMethod", "Density (kg/m3)", "Density", "User-defined EOS Density");
    setVaporEnthalpyAndSpecificHeat(material, table);
    setTemperatureTable(material, table, "star.energy.PolynomialDensityProperty", "star.energy.DensityTemperatureTableDT", "Density (kg/m3)", "Density", "Density");
    setTemperatureTable(material, table, "star.flow.ConstantDensityProperty", "star.energy.DensityTemperatureTableDT", "Density (kg/m3)", "Density", "Constant Density fallback");
    setTemperatureTable(material, table, "star.energy.ThermalConductivityProperty", "star.energy.TemperatureTableMethod", "Equivalent Thermal Conductivity (W/m-K)", "Equivalent Thermal Conductivity", "Thermal Conductivity");
    setTemperatureTable(material, table, "star.flow.DynamicViscosityProperty", "star.energy.TemperatureTableMethod", "Equivalent Dynamic Viscosity (Pa-s)", "Equivalent Dynamic Viscosity", "Dynamic Viscosity");
  }}

  private void setVaporEnthalpyAndSpecificHeat(Material material, Table table) {{
    boolean enthalpyBound = setTemperatureTable(material, table, "star.userdefinedeos.UserDefinedEnthalpyProperty", "star.energy.EnthalpyTemperatureTable", "Enthalpy (J/kg)", "Enthalpy", "User-defined EOS Enthalpy");
    if ("enthalpy_table".equals(VAPOR_SPECIFIC_HEAT_SOURCE)) {{
      if (enthalpyBound) {{
        sim.println("[refprop-to-ccm] Using user-defined EOS enthalpy table as vapor specific heat source.");
      }}
      return;
    }}
    setTemperatureTable(material, table, "star.energy.SpecificHeatProperty", "star.userdefinedeos.UserDefinedSpecificHeatTemperatureTable", "Equivalent Specific Heat (J/kg-K)", "Equivalent Specific Heat", "User-defined EOS Specific Heat Cp(T)");
  }}

  private boolean setConstant(Material material, String propertyClassName, double value, String label) {{
    try {{
      Class propertyClass = Class.forName(propertyClassName);
      MaterialProperty property = (MaterialProperty) material.getMaterialProperties().getMaterialProperty(propertyClass);
      property.setConstant(value);
      sim.println("[refprop-to-ccm] Set " + label + " = " + value);
      return true;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Could not set " + label + " via " + propertyClassName + ": " + ex.getMessage());
      return false;
    }}
  }}

  private boolean setTemperatureTable(Material material, Table table, String propertyClassName, String methodClassName, String dataColumn, String fallbackDataColumn, String label) {{
    try {{
      Class propertyClass = Class.forName(propertyClassName);
      Class methodClass = Class.forName(methodClassName);
      MaterialProperty property = (MaterialProperty) material.getMaterialProperties().getMaterialProperty(propertyClass);
      property.setMethod(methodClass);
      MaterialPropertyMethod method = (MaterialPropertyMethod) property.getMaterialPropertyMethod(methodClass);
      Object interpolation = method.getClass().getMethod("getInterpolationTable").invoke(method);
      interpolation.getClass().getMethod("setTable", Table.class).invoke(interpolation, table);
      setTableColumn(interpolation, "setT", "Temperature (C)", "Temperature", "Temperature");
      setTableColumn(interpolation, "setData", dataColumn, fallbackDataColumn, label);
      sim.println("[refprop-to-ccm] Bound " + label + " to table column: " + dataColumn + " / " + fallbackDataColumn);
      return true;
    }} catch (Throwable ex) {{
      sim.println("[refprop-to-ccm] Could not bind " + label + " table via " + propertyClassName + " / " + methodClassName + ": " + ex.getMessage());
      return false;
    }}
  }}

  private void setTableColumn(Object interpolation, String setterName, String preferred, String fallback, String label) throws Exception {{
    try {{
      interpolation.getClass().getMethod(setterName, String.class).invoke(interpolation, preferred);
    }} catch (Throwable preferredEx) {{
      sim.println("[refprop-to-ccm] Preferred table column failed for " + label + ": " + preferred + " -> " + preferredEx.getMessage());
      interpolation.getClass().getMethod(setterName, String.class).invoke(interpolation, fallback);
    }}
  }}

  private void writeLiquidValuesToLog() {{
    sim.println("[refprop-to-ccm] Liquid saturated properties:");
    sim.println("  Liquid Property Mode = " + LIQUID_PROPERTY_MODE);
    sim.println("  Liquid table path = " + LIQUID_TABLE);
    sim.println("  Saturation Temperature K = {liquid.saturation_temperature_k:.12g}");
    sim.println("  Saturation Pressure Pa = {liquid.saturation_pressure_pa:.12g}");
    sim.println("  Specific Heat J/kg-K = {liquid.specific_heat_j_per_kg_k:.12g}");
    sim.println("  Standard State Temperature K = {liquid.standard_state_temperature_k:.12g}");
    sim.println("  Thermal Conductivity W/m-K = {liquid.thermal_conductivity_w_per_m_k:.12g}");
    sim.println("  Dynamic Viscosity Pa-s = {liquid.dynamic_viscosity_pa_s:.12g}");
    sim.println("  Polynomial Density kg/m3 = {liquid.density_kg_per_m3:.12g}");
    sim.println("  Molecular Weight kg/kmol = {liquid.molecular_weight_kg_per_kmol:.12g}");
    sim.println("  Saturated Liquid Enthalpy J/kg = {liquid.saturated_liquid_enthalpy_j_per_kg:.12g}");
    sim.println("  Saturated Vapor Enthalpy J/kg = {liquid.saturated_vapor_enthalpy_j_per_kg:.12g}");
    sim.println("  Liquid Standard State Enthalpy / Heat of Formation input J/kg = {liquid.liquid_standard_state_enthalpy_j_per_kg:.12g}");
    sim.println("  Vapor Standard State Enthalpy / Heat of Formation input J/kg = {liquid.vapor_standard_state_enthalpy_j_per_kg:.12g}");
    sim.println("  Density Temperature Derivative kg/m3-K = {liquid.density_temperature_derivative_kg_per_m3_k:.12g}");
    sim.println("  Vapor Specific Heat Source = " + VAPOR_SPECIFIC_HEAT_SOURCE);
  }}
}}
"""


class StarCcmRunner:
    def __init__(self, config: ToolConfig) -> None:
        self.config = config

    def run(self, macro_file: Path) -> Path:
        if self.config.starccm_exe is None:
            raise ValueError("starccm.starccm_exe is required unless --no-run-star is used.")
        if not self.config.starccm_exe.exists():
            raise FileNotFoundError(f"STAR-CCM+ executable does not exist: {self.config.starccm_exe}")
        if not self.config.sim_file.exists():
            raise FileNotFoundError(f"STAR-CCM+ sim file does not exist: {self.config.sim_file}")

        command = [
            str(self.config.starccm_exe),
            "-batch",
            str(macro_file),
            str(self.config.sim_file),
        ]
        log_file = self.config.output_directory / "starccm_run.log"
        with log_file.open("w", encoding="utf-8", errors="replace") as handle:
            handle.write("Command:\n")
            handle.write(" ".join(command))
            handle.write("\n\nOutput:\n")
            completed = subprocess.run(
                command,
                stdout=handle,
                stderr=subprocess.STDOUT,
                text=True,
                check=False,
            )
        if completed.returncode != 0:
            raise RuntimeError(f"STAR-CCM+ run failed with exit code {completed.returncode}. Log: {log_file.resolve()}")
        return log_file.resolve()


def _java(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
